jwt:
  secret: fj38fj93jf83jg84hg84hg48hg84hg48jg84jg84jg48jg84jg84
  lifetime: 30m
spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
    url: jdbc:mysql://database1.ccinsbk6pi2w.us-east-1.rds.amazonaws.com:3306/spring_security_db
    username: root
    password: administrator
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    hikari:
  #      maximum-pool-size: 10
  #      connection-timeout: 30000
  #      idle-timeout: 600000
  #    url: jdbc:mysql://localhost:3306/spring_security_db
  #    username: root
  #    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
